### ISSUE TITLE
panic: open ".jxml" no such file or directory 

### ISSUE THREAD

**Issue by jerryfane** [lootag/ImageAuGomentationCLI#2]
When trying to start the augmentation, it seems that the program tries to look for ".jxml" files instead of ".xml" and fails to complete the action. I already double-checked that these files exist in my Annotations directory as ".xml"

```
jerry@Jerrys-MacBook-Pro dl_images % ../ImageAuGomentationCLI/ImageAuGomentationCLI -blur=3
panic: open ./Annotations/100.983e401b-b2c5-487a-ad79-7d71fa3f9c1b_1.8ee547d8766948677add353c270bdd28.jxml: no such file or directory

goroutine 7 [running]:
github.com/lootag/ImageAuGomentationCLI/annotationReaders.PascalVocReader.ReadSync(0xc000434000, 0x5e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jerry/Desktop/DSBA/Second Year/Deep Learning for Computer Vision/Lab-Logo/ImageAuGomentationCLI/annotationReaders/PascalVocReader.go:51 +0x46d
github.com/lootag/ImageAuGomentationCLI/exclusion.readAnnotations(0x0, 0xc0001973d0, 0xc000020300, 0xc000020360)
	/Users/jerry/Desktop/DSBA/Second Year/Deep Learning for Computer Vision/Lab-Logo/ImageAuGomentationCLI/exclusion/ExclusionService.go:74 +0xf9
created by github.com/lootag/ImageAuGomentationCLI/exclusion.ExclusionService.GetClassesToExclude
	/Users/jerry/Desktop/DSBA/Second Year/Deep Learning for Computer Vision/Lab-Logo/ImageAuGomentationCLI/exclusion/ExclusionService.go:38 +0x150
```

**Comment by lootag** [comment]
Hey Jerry,
 I'm pretty sure that that's because you have your files as .jpeg instead of  .jpg. I'll fix it by monday, but in the meantime make sure that all your files are .jpg.

Let me know if the utility works correctly once you have renamed your files 😃

**Comment by jerryfane** [comment]
I have renamed all jpegs to jpg, and indeed it no longer seems to give error for "jxml" files. 

Unfortunately every time I run the augment process, it still outputs an error for a certain file "./Annotations/.DS_Stxml", which I suppose is a hidden file inside the Images folder, but I don't understand what file it is and how to remove it. 



```
jerry@Jerrys-MacBook-Pro dl_images % augoment -batch_size=50 -blur=3
panic: open ./Annotations/.DS_Stxml: no such file or directory

goroutine 7 [running]:
github.com/lootag/ImageAuGomentationCLI/annotationReaders.PascalVocReader.ReadSync(0xc0004800c0, 0x17, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/jerry/Desktop/DSBA/Second Year/Deep Learning for Computer Vision/Lab-Logo/dl_images/ImageAuGomentationCLI/annotationReaders/PascalVocReader.go:51 +0x46d
github.com/lootag/ImageAuGomentationCLI/exclusion.readAnnotations(0x0, 0xc0001953f0, 0xc000020300, 0xc000020360)
	/Users/jerry/Desktop/DSBA/Second Year/Deep Learning for Computer Vision/Lab-Logo/dl_images/ImageAuGomentationCLI/exclusion/ExclusionService.go:74 +0xf9
created by github.com/lootag/ImageAuGomentationCLI/exclusion.ExclusionService.GetClassesToExclude
	/Users/jerry/Desktop/DSBA/Second Year/Deep Learning for Computer Vision/Lab-Logo/dl_images/ImageAuGomentationCLI/exclusion/ExclusionService.go:38 +0x150
```

**Comment by lootag** [comment]
cd into the images folder, and run "rm  .DS_Stmjpg". 
If it says you got no permission to do that, just sudo it.

Keep me posted 😃

**Comment by jerryfane** [comment]
I tried ```find . -name '.DS_Store' -type f -delete``` into `Images` and now it seems to work fine:)

**Comment by lootag** [comment]
That's great 😃 let me know if you run into other problems, I'm going to close the issue now.
